controller_list:
  - name: fake_robot_arm_controller
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
  - name: fake_gripper_controller
    joints:
      - Joint6